services:
  backend:
    container_name: backend
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    ports:
      - 3001:3001
    env_file:
      - sample.env
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - sample.env
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    user: "${UID}:${GID}"
    env_file:
      - sample.env
    volumes:
      - ./pgadmin4:/var/lib/pgadmin
    ports:
      - 5433:80
    depends_on:
      - postgres
