services:
  backend:
    container_name: backend
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    ports:
      - 3001:3001
    env_file:
      - sample.env
    depends_on:
      postgres:
        condition: service_healthy

    # we need to apply the migrations before we run the app,
    # otherwise, the container will restart infinitely.
    # Running the first one in the Dockerfile won't work because
    # the database isn't running at that point
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma db seed &&
             npm run start:dev"
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - sample.env
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    user: "${UID}:${GID}"
    env_file:
      - sample.env
    volumes:
      - ./pgadmin4:/var/lib/pgadmin
    ports:
      - 5433:80
    depends_on:
      - postgres
